development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d56anon42gtdta
  username: lccpjuwgweidin
  password: qkpxnKIzAPlNoiMYvGQOD08OxX
  host: ec2-54-221-227-25.compute-1.amazonaws.com
  port: 5432